apiVersion: v1
kind: Service
metadata:
  name: django-gunicorn-service
spec:
  selector:
    app: django-gunicorn 
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
